
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Alignment alignment11;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Alignment RawLabelAlignment;

	private global::Gtk.Label label3;

	private global::Gtk.Alignment TextInputAlignment;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView InputRawText;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label5;

	private global::Gtk.Alignment KeyEntryAlignment;

	private global::Gtk.Entry KeyCipherEntry;

	private global::Gtk.Alignment CipherButtonAlignment;

	private global::Gtk.Button CipherButton;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView CipherOutput;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.Label label10;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Alignment alignment12;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Alignment RawLabelAlignment1;

	private global::Gtk.Label label4;

	private global::Gtk.Alignment TextInputAlignment1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView InputSecretText;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label6;

	private global::Gtk.Alignment KeyEntryAlignment1;

	private global::Gtk.Entry KeyDecipherEntry;

	private global::Gtk.Alignment CipherButtonAlignment1;

	private global::Gtk.Button DecipherButton;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView RawOutput;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Label label11;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Szyfrator 1");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment11.Name = "alignment11";
		this.alignment11.TopPadding = ((uint)(10));
		// Container child alignment11.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.RawLabelAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.RawLabelAlignment.Name = "RawLabelAlignment";
		this.RawLabelAlignment.RightPadding = ((uint)(3));
		this.RawLabelAlignment.BottomPadding = ((uint)(290));
		// Container child RawLabelAlignment.Gtk.Container+ContainerChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 150;
		this.label3.HeightRequest = 10;
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Tekst w postaci jawnej:");
		this.RawLabelAlignment.Add(this.label3);
		this.hbox1.Add(this.RawLabelAlignment);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.RawLabelAlignment]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.TextInputAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.TextInputAlignment.Name = "TextInputAlignment";
		this.TextInputAlignment.RightPadding = ((uint)(100));
		// Container child TextInputAlignment.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.InputRawText = new global::Gtk.TextView();
		this.InputRawText.WidthRequest = 655;
		this.InputRawText.HeightRequest = 300;
		this.InputRawText.CanFocus = true;
		this.InputRawText.Name = "InputRawText";
		this.InputRawText.WrapMode = ((global::Gtk.WrapMode)(2));
		this.InputRawText.PixelsBelowLines = 6;
		this.InputRawText.LeftMargin = 1;
		this.InputRawText.RightMargin = 1;
		this.GtkScrolledWindow.Add(this.InputRawText);
		this.TextInputAlignment.Add(this.GtkScrolledWindow);
		this.hbox1.Add(this.TextInputAlignment);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.TextInputAlignment]));
		w5.Position = 1;
		this.alignment11.Add(this.hbox1);
		this.vbox1.Add(this.alignment11);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment11]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 150;
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Klucz szyfrujący:");
		this.label5.Justify = ((global::Gtk.Justification)(1));
		this.hbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label5]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.KeyEntryAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.KeyEntryAlignment.Name = "KeyEntryAlignment";
		this.KeyEntryAlignment.RightPadding = ((uint)(4));
		// Container child KeyEntryAlignment.Gtk.Container+ContainerChild
		this.KeyCipherEntry = new global::Gtk.Entry();
		this.KeyCipherEntry.CanFocus = true;
		this.KeyCipherEntry.Name = "KeyCipherEntry";
		this.KeyCipherEntry.IsEditable = true;
		this.KeyCipherEntry.InvisibleChar = '●';
		this.KeyEntryAlignment.Add(this.KeyCipherEntry);
		this.hbox3.Add(this.KeyEntryAlignment);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.KeyEntryAlignment]));
		w10.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.CipherButtonAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.CipherButtonAlignment.Name = "CipherButtonAlignment";
		this.CipherButtonAlignment.RightPadding = ((uint)(37));
		// Container child CipherButtonAlignment.Gtk.Container+ContainerChild
		this.CipherButton = new global::Gtk.Button();
		this.CipherButton.CanFocus = true;
		this.CipherButton.Name = "CipherButton";
		this.CipherButton.UseUnderline = true;
		this.CipherButton.Label = global::Mono.Unix.Catalog.GetString("Szyfruj");
		this.CipherButtonAlignment.Add(this.CipherButton);
		this.hbox3.Add(this.CipherButtonAlignment);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.CipherButtonAlignment]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.GtkAlignment.TopPadding = ((uint)(10));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.CipherOutput = new global::Gtk.TextView();
		this.CipherOutput.CanFocus = true;
		this.CipherOutput.Name = "CipherOutput";
		this.CipherOutput.Editable = false;
		this.CipherOutput.CursorVisible = false;
		this.CipherOutput.AcceptsTab = false;
		this.GtkScrolledWindow1.Add(this.CipherOutput);
		this.GtkAlignment.Add(this.GtkScrolledWindow1);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Wynik:</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add(this.frame1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
		w17.Position = 2;
		this.notebook1.Add(this.vbox1);
		// Notebook tab
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Szyfrowanie");
		this.notebook1.SetTabLabel(this.vbox1, this.label10);
		this.label10.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment12.Name = "alignment12";
		this.alignment12.TopPadding = ((uint)(10));
		// Container child alignment12.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.RawLabelAlignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.RawLabelAlignment1.Name = "RawLabelAlignment1";
		this.RawLabelAlignment1.LeftPadding = ((uint)(3));
		this.RawLabelAlignment1.BottomPadding = ((uint)(290));
		// Container child RawLabelAlignment1.Gtk.Container+ContainerChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 150;
		this.label4.HeightRequest = 10;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Zaszyfrowany tekst:");
		this.RawLabelAlignment1.Add(this.label4);
		this.hbox2.Add(this.RawLabelAlignment1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.RawLabelAlignment1]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.TextInputAlignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.TextInputAlignment1.Name = "TextInputAlignment1";
		this.TextInputAlignment1.RightPadding = ((uint)(100));
		// Container child TextInputAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.InputSecretText = new global::Gtk.TextView();
		this.InputSecretText.WidthRequest = 655;
		this.InputSecretText.HeightRequest = 300;
		this.InputSecretText.CanFocus = true;
		this.InputSecretText.Name = "InputSecretText";
		this.InputSecretText.WrapMode = ((global::Gtk.WrapMode)(2));
		this.InputSecretText.PixelsBelowLines = 6;
		this.InputSecretText.LeftMargin = 1;
		this.InputSecretText.RightMargin = 1;
		this.GtkScrolledWindow2.Add(this.InputSecretText);
		this.TextInputAlignment1.Add(this.GtkScrolledWindow2);
		this.hbox2.Add(this.TextInputAlignment1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.TextInputAlignment1]));
		w23.Position = 1;
		this.alignment12.Add(this.hbox2);
		this.vbox2.Add(this.alignment12);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment12]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.WidthRequest = 150;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Klucz deszyfrujący:");
		this.label6.Justify = ((global::Gtk.Justification)(1));
		this.hbox4.Add(this.label6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label6]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.KeyEntryAlignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.KeyEntryAlignment1.Name = "KeyEntryAlignment1";
		this.KeyEntryAlignment1.RightPadding = ((uint)(4));
		// Container child KeyEntryAlignment1.Gtk.Container+ContainerChild
		this.KeyDecipherEntry = new global::Gtk.Entry();
		this.KeyDecipherEntry.CanFocus = true;
		this.KeyDecipherEntry.Name = "KeyDecipherEntry";
		this.KeyDecipherEntry.IsEditable = true;
		this.KeyDecipherEntry.InvisibleChar = '●';
		this.KeyEntryAlignment1.Add(this.KeyDecipherEntry);
		this.hbox4.Add(this.KeyEntryAlignment1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.KeyEntryAlignment1]));
		w28.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.CipherButtonAlignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.CipherButtonAlignment1.Name = "CipherButtonAlignment1";
		this.CipherButtonAlignment1.RightPadding = ((uint)(24));
		// Container child CipherButtonAlignment1.Gtk.Container+ContainerChild
		this.DecipherButton = new global::Gtk.Button();
		this.DecipherButton.CanFocus = true;
		this.DecipherButton.Name = "DecipherButton";
		this.DecipherButton.UseUnderline = true;
		this.DecipherButton.Label = global::Mono.Unix.Catalog.GetString("Odszyfruj");
		this.CipherButtonAlignment1.Add(this.DecipherButton);
		this.hbox4.Add(this.CipherButtonAlignment1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.CipherButtonAlignment1]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		this.GtkAlignment1.TopPadding = ((uint)(10));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.RawOutput = new global::Gtk.TextView();
		this.RawOutput.CanFocus = true;
		this.RawOutput.Name = "RawOutput";
		this.RawOutput.Editable = false;
		this.RawOutput.CursorVisible = false;
		this.RawOutput.AcceptsTab = false;
		this.GtkScrolledWindow3.Add(this.RawOutput);
		this.GtkAlignment1.Add(this.GtkScrolledWindow3);
		this.frame2.Add(this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Wynik:</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.vbox2.Add(this.frame2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
		w35.Position = 2;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w36 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w36.Position = 1;
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Odszyfrowanie");
		this.notebook1.SetTabLabel(this.vbox2, this.label11);
		this.label11.ShowAll();
		this.Add(this.notebook1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1030;
		this.DefaultHeight = 680;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyCipherEntry.Changed += new global::System.EventHandler(this.OnKeyCipherEntryChanged);
		this.CipherButton.Clicked += new global::System.EventHandler(this.OnCipherButtonClicked);
		this.DecipherButton.Clicked += new global::System.EventHandler(this.OnDecipherButtonClicked);
	}
}
